### PR TITLE
ODLC Submission Page

### LINKED ISSUE #46: Frontend ODLC Submission Interface
The frontend ODLC submission interface currently does not work. This is required for the AUVSI SUAS competition.

### PR DESCRIPTION
**Pull request by pizzalemon**
The ODLC submission page for the client. I still need to fix a UI thing on the Submitted tab, and I haven't taken a close look at the changes yet and commit structure, etc., so this is still just a draft.

### CODE REVIEW

**Comment by pizzalemon** [comment]
So everything should be in a workable state now. I've changed quite a few things (including some backend stuff). While it is in a working state, there's a little bit of functionality missing:

- buttons for downloading and uploading images into the program, so they can be edited outside of the program
- possible that some editing the program could work well too, like built in cropping
- a button which just converts ODLCs between standard and emergent
- making the the emergent description box expand based on the amount of text within it (not really needed, but it would nice)

I reiterate that the PR is in a working condition, so despite the missing functionality, it's still worth your time to review it, if you do have the time.

**Comment by pizzalemon** [comment]
So the page should have all the basic features it needs now. I'm trying to see if I can squash the commits all into one, but the commit history is weird because of merges.

File: client/src/pages/Submissions/index.js [hunk 1]
```diff
@@ -1,39 +1,137 @@
...
+	}
+
+	const edit = async (i, formData) => {
+		let d = data
+		let odlc = d[i]
+		d[i] = formData
+		odlc = convertOdlc(d[i])
+		setData(d)
+		console.log(formData)
+		await httppost("/interop/odlc/edit/"+i, { ...odlc, image: images[i] })
```
Comment (krishnans2006) [inline client/src/pages/Submissions/index.js:119]: Are we not going to refresh the page after any edits? Because the images do not update after a save (although the data does carry over). I feel like refreshing the page on edit makes it much clearer for someone to know that they have changed an image.

File: client/src/pages/Submissions/index.js [hunk 2]
```diff
@@ -1,39 +1,137 @@
...
+	const convertOdlc = (o) => {
+		return { ...o, orientation: o.orientation/45+1 }
+	}
+
+	const accept = async (i, formData) => {
+		let d = data
+		if (formData) {
+			d[i] = formData
+			let submit = convertOdlc(d[i])
+			await httppost("/interop/odlc/edit/"+i, submit)
```
Comment (krishnans2006) [inline client/src/pages/Submissions/index.js]: Edge Case: When editing an image and directly submitting (without manually saving the ODLC), the image updates correctly on the frontend, but a refresh shows that the ODLC did not save correctly with the new image. The Interop Server also does not reflect changes to the image if not specifically saved. Since submitting an ODLC also saves it's data, you should make it so the submit button also saves the ODLC correctly.

```suggestion
			await httppost("/interop/odlc/edit/"+i, { ...submit, image: images[i] })
```

**Review by krishnans2006 — CHANGES_REQUESTED** [review]
Overall, it mostly works correctly and is functional, which is all that we basically need. Other than fixing these minor issues, you're good to go for the PR!

File: client/src/pages/Submissions/index.js (hunk 1 above)
Comment (pizzalemon) [reply client/src/pages/Submissions/index.js:119]: I forgot to change that.

**Review by krishnans2006 — APPROVED** [review]
Perfect!
